name: Run Two

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main, canary]
    types:
      - completed

jobs:
  two:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"

      - name: workflow 2
        run: |
          echo "workflow 2 complete"