name: CD

on:
  workflow_run:
    workflows:
      - "CI"
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v3"

      - name: workflow 2
        run: |
          echo "workflow 2 complete"