name: Node.js CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: "npm install"
        run: |
          echo "npm install"
          npm ci

      - name: "Lint code"
        run: |
          echo "Linting repository"
          npm run lint

      - name: "Run audit"
        run: |
          echo "Running unit tests"
          npm audit

      - name: "Run unit tests"
        run: |
          echo "Running unit tests"
          npm test

  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"